# Site settings
title: Marco is live at Netlify
email: marcoadmateus@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello and Welcome to my application.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: marcoislive@netlify (not in production)
github_username: mphoebos

# Build settings
markdown: kramdown
include: [_redirects]
